// ============================================================
// lib/hooks/useRegistration.ts — Multi-step form state
// ============================================================
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export type Step1Data = {
  first_name_ar: string; last_name_ar: string
  first_name_en: string; last_name_en: string
  date_of_birth: string; sex: 'M' | 'F'
  nationality: string; marital_status: string; occupation: string
  mobile_primary: string; email: string
  governorate: string; district: string
  emergency_name: string; emergency_relation: string; emergency_phone: string
  referral_source: string; referring_provider: string
  nid: string; insurance_id: string; passport: string
}

export function useRegistration() {
  const [step, setStep] = useState(1)
  const [patientId, setPatientId] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const supabase = createClient()

  // STEP 1 — Receptionist creates patient
  async function saveStep1(data: Step1Data) {
    setSaving(true); setError(null)
    try {
      // Insert patient (MRN auto-generated by trigger)
      const { data: patient, error: err } = await supabase
        .from('patients')
        .insert({
          mrn: '',   // trigger replaces this
          first_name_ar: data.first_name_ar,
          last_name_ar:  data.last_name_ar,
          first_name_en: data.first_name_en.toLowerCase(),
          last_name_en:  data.last_name_en.toLowerCase(),
          date_of_birth: data.date_of_birth,
          sex:           data.sex,
          nationality:   data.nationality,
          marital_status: data.marital_status || null,
          occupation:    data.occupation || null,
          mobile_primary: data.mobile_primary,
          email:         data.email || null,
          governorate:   data.governorate,
          district:      data.district,
          emergency_name:     data.emergency_name,
          emergency_relation: data.emergency_relation,
          emergency_phone:    data.emergency_phone,
          referral_source:    data.referral_source || null,
          referring_provider: data.referring_provider || null,
        })
        .select('id,mrn')
        .single()

      if (err) throw err

      // Insert identity documents
      const identities = [
        { id_type: 'NID',       id_number: data.nid },
        { id_type: 'INSURANCE', id_number: data.insurance_id },
        { id_type: 'PASSPORT',  id_number: data.passport },
      ].filter(i => i.id_number?.trim())

      if (identities.length > 0) {
        await supabase.from('patient_identities').insert(
          identities.map(i => ({ ...i, patient_id: patient!.id }))
        )
      }

      // Consents auto-created by DB trigger
      setPatientId(patient!.id)
      setStep(2)
      return patient
    } catch (e: any) {
      setError(e.message)
      return null
    } finally {
      setSaving(false)
    }
  }

  // STEP 2 — Doctor saves medical data
  async function saveStep2(data: any) {
    if (!patientId) return
    setSaving(true); setError(null)
    try {
      // Diagnosis
      const { data: diag, error: diagErr } = await supabase
        .from('diagnoses')
        .insert({ patient_id: patientId, ...data.diagnosis })
        .select('id').single()
      if (diagErr) throw diagErr

      // Biomarkers
      await supabase.from('biomarkers')
        .insert({ patient_id: patientId, diagnosis_id: diag.id, ...data.biomarkers })

      // Medical history (includes ECOG + BSA — BSA auto-calc by trigger)
      await supabase.from('medical_history')
        .insert({ patient_id: patientId, ...data.history })

      setStep(3)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setSaving(false)
    }
  }

  // STEP 3 — Insurance + payment
  async function saveStep3(data: any) {
    if (!patientId) return
    setSaving(true); setError(null)
    try {
      await supabase.from('insurance_policies')
        .insert({ patient_id: patientId, ...data.insurance })
      await supabase.from('payment_plans')
        .insert({ patient_id: patientId, ...data.payment })
      setStep(4)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setSaving(false)
    }
  }

  // STEP 4 — Sign consent
  async function signConsent(consentType: string) {
    if (!patientId) return
    const { error: err } = await supabase
      .from('consents')
      .update({
        status: 'signed',
        signed_by_patient: true,
        signed_at: new Date().toISOString(),
      })
      .eq('patient_id', patientId)
      .eq('consent_type', consentType)
    if (err) setError(err.message)
  }

  async function completeRegistration() {
    // Verify all required consents signed
    const { data: consents } = await supabase
      .from('consents')
      .select('consent_type,status,is_required')
      .eq('patient_id', patientId!)
    const allSigned = consents
      ?.filter(c => c.is_required)
      .every(c => c.status === 'signed')
    if (!allSigned) {
      setError('يرجى توقيع جميع الموافقات الإلزامية')
      return false
    }
    return true
  }

  return {
    step, setStep, patientId, saving, error,
    saveStep1, saveStep2, saveStep3, signConsent, completeRegistration,
  }
}